In [1]:
import pandas as pd

In [2]:
df_users = pd.read_csv("/Users/athipongjindaphram/Documents/E-Commerce_Product_Intelligence_Project/data/users.csv")
df_sessions = pd.read_csv("/Users/athipongjindaphram/Documents/E-Commerce_Product_Intelligence_Project/data/sessions.csv")
df_reviews = pd.read_csv("/Users/athipongjindaphram/Documents/E-Commerce_Product_Intelligence_Project/data/reviews.csv")
df_purchases = pd.read_csv("/Users/athipongjindaphram/Documents/E-Commerce_Product_Intelligence_Project/data/purchases.csv")
df_products = pd.read_csv("/Users/athipongjindaphram/Documents/E-Commerce_Product_Intelligence_Project/data/products.csv")
df_interactions = pd.read_csv("/Users/athipongjindaphram/Documents/E-Commerce_Product_Intelligence_Project/data/interactions.csv")

In [3]:
df_users.head()

,user_id,age,gender,country,city,signup_date,income_level,preferred_category,loyalty_tier
0,8826d916-cdfb-41c6-81ff-91a761565a70,18,Female,US,Changchester,2026-02-05,medium,Sports & Outdoors,bronze
1,2416da6e-c212-4ddb-8d88-00160eb686b2,32,Female,AU,New Tammyfort,2025-03-03,very_high,Automotive,bronze
2,eb819333-b501-4c18-8c53-c786ed62c2f9,18,Male,US,Hullport,2025-03-12,medium,Books,bronze
3,71445abc-2f0d-4ac2-8097-acb7a3823bc9,58,Female,US,Howardborough,2025-09-21,low,Beauty & Personal Care,bronze
4,13d16283-160e-4c20-aebd-f9d6297e4c73,38,Female,US,West Donald,2024-07-11,medium,Electronics,bronze

In [4]:
df_users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   user_id             10000 non-null  object
 1   age                 10000 non-null  int64
 2   gender              10000 non-null  object
 3   country             10000 non-null  object
 4   city                10000 non-null  object
 5   signup_date         10000 non-null  object
 6   income_level        10000 non-null  object
 7   preferred_category  10000 non-null  object
 8   loyalty_tier        10000 non-null  object
dtypes: int64(1), object(8)
memory usage: 703.3+ KB

In [5]:
df_users.isnull().sum()

user_id               0
age                   0
gender                0
country               0
city                  0
signup_date           0
income_level          0
preferred_category    0
loyalty_tier          0
dtype: int64

In [6]:
df_sessions.head()

,session_id,user_id,start_time,device_type,referrer_source,is_converted
0,6d553c2d-fe1e-4406-9e32-cd258df05830,0000780a-2126-4e84-9622-42ce0ea9b17a,2023-01-16 12:57:18.000000115,desktop,organic_search,False
1,7330ad09-21cd-4849-b1c8-528d72f7d23b,0000780a-2126-4e84-9622-42ce0ea9b17a,2023-01-18 09:20:23.000000548,desktop,display_ad,False
2,6f6dce62-c078-4dfd-b39b-33068358bc0a,000aea63-23ad-42ab-98b8-3de2e33c624c,2024-10-17 02:05:24.000000257,desktop,direct,False
3,d3a0ecd7-69c3-431e-bab2-89946ce644c1,000b86cc-387b-4968-aaa5-7152296985d2,2026-02-11 03:24:48.000000440,mobile,direct,False
4,1539d203-2ced-4a39-b32c-79caf3b0db72,000b86cc-387b-4968-aaa5-7152296985d2,2026-02-12 16:41:52.000000696,mobile,organic_search,False

In [7]:
df_sessions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19315 entries, 0 to 19314
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   session_id       19315 non-null  object
 1   user_id          19315 non-null  object
 2   start_time       19315 non-null  object
 3   device_type      19315 non-null  object
 4   referrer_source  19315 non-null  object
 5   is_converted     19315 non-null  bool
dtypes: bool(1), object(5)
memory usage: 773.5+ KB

In [8]:
df_sessions.isnull().sum()

session_id         0
user_id            0
start_time         0
device_type        0
referrer_source    0
is_converted       0
dtype: int64

In [9]:
df_reviews.head()

,review_id,user_id,product_id,purchase_id,rating,title,review_text,review_date
0,e4ad6f1e-6449-4793-a131-17192b03e509,f6cadab8-2be9-4480-a278-71846245a809,99aee34b-3b16-4337-8132-f183349dfd69,NaN,4,A reliable purchase,This Staples Organization Set does exactly wha...,2022-01-13 00:00:00.000000000
1,0c5734c1-dacb-4028-a50a-507ca9c92aeb,d89694d2-292d-42d4-b090-947c1e292c98,38685bcb-3aef-4d81-abeb-101f9beee4fd,NaN,5,This Studio: A Comprehensive Guide is a game c...,I did not expect to love this as much as I do....,2022-01-15 00:00:00.000000000
2,d978ff74-a828-4f62-b550-f70664aca6aa,4f92de48-e30b-49e8-9584-8868945497d0,aba49dc2-3182-4614-a4ad-e2b537d50b04,NaN,4,Very satisfied with this Cuisinart Non-Stick K...,This Cuisinart Non-Stick Kitchenware has held ...,2022-01-26 00:00:00.000000000
3,50332ba8-4577-439d-8111-ef0b5960acd5,845e33f0-1aab-4df5-9a49-0a50fd5a4298,d30b76ee-5a18-4e36-bbb7-84723460be23,NaN,3,Not bad but not great either,This Fitness for Professionals gets the job do...,2022-02-02 00:00:00.000000000
4,8bdb7c01-41cf-44cb-99c9-8862c5d833b0,0da6cc24-2cd4-42dc-88e8-137951cd5ef5,61113e39-9a12-48a9-840b-dd7368dca11c,NaN,3,Function over form,This MSR Performance Cycling works fine but th...,2022-02-08 00:00:00.000000000

In [10]:
df_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1253 entries, 0 to 1252
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    1253 non-null   object
 1   user_id      1253 non-null   object
 2   product_id   1253 non-null   object
 3   purchase_id  1053 non-null   object
 4   rating       1253 non-null   int64
 5   title        1253 non-null   object
 6   review_text  1253 non-null   object
 7   review_date  1253 non-null   object
dtypes: int64(1), object(7)
memory usage: 78.4+ KB

In [11]:
df_reviews.isnull().sum()

review_id        0
user_id          0
product_id       0
purchase_id    200
rating           0
title            0
review_text      0
review_date      0
dtype: int64

In [12]:
df_purchases.head()

,purchase_id,order_id,user_id,product_id,session_id,interaction_id,quantity,unit_price,total_amount,order_date
0,6a57a9c2-5d12-441f-8bde-2781458c6da7,b5d39dff-18ce-4032-8d8d-02db73e5c09e,d669cbc4-2606-49ef-b643-b902b1f0b196,af3bccbc-763f-4162-a178-bf20bfaeccba,003fc1af-ae18-4436-acd7-e4936459c620,ce36fbcb-a957-4388-8717-b8cf3041685a,2,5.74,11.48,2023-01-15 18:05:44.055402424
1,4d758486-b0bd-41d5-84cc-921d01ec3a6a,924f67e7-aac8-49bd-abc7-19339a24fb85,dfd9ccd9-9288-45cd-a1cf-f9c08e2a1b37,0c70a612-d55e-4879-9bce-299d323437f3,6106d434-cac5-40b3-b2a5-0d88a989ed26,9e36d37a-f610-483a-88e0-33b14973265f,2,79.42,158.84,2023-01-19 18:02:11.094635944
2,014ee443-7bdc-4a83-9f9c-4977a112758d,d7ee3884-ce84-451c-876c-2f7fef3d9751,056ebd8a-199a-47fe-867d-8e1698993134,920a8047-d219-4f21-bf1e-9904f1097bad,15bf8d57-5b7d-46a6-9ea9-df3b5ab3c941,d4462a4c-4f04-4b9c-b66d-1e0c82b58377,1,10.71,10.71,2023-01-31 19:52:13.995509927
3,5517e5d5-59ed-4c0b-8e23-1a50d851b33d,d7ee3884-ce84-451c-876c-2f7fef3d9751,056ebd8a-199a-47fe-867d-8e1698993134,5d836ef6-20f0-47c1-9a54-791a4bfeded1,15bf8d57-5b7d-46a6-9ea9-df3b5ab3c941,a24d3211-ac7f-4e4d-9c38-820225b51b67,1,16.21,16.21,2023-01-31 19:52:36.542442866
4,1aef1fd5-cdd4-4e31-9c7c-e6e620bb0386,00c0ba74-a756-4ebf-8748-d9970e12bf38,ada8b2e5-53bb-489a-b8a7-e9a013f4d886,6651c3ab-c7be-4131-b324-68bd0218eb2c,0d07cf8a-4d46-4c9d-a6bd-bcb295d692b7,5aeb69e3-e174-41dd-bc7f-923650d78204,4,67.97,271.88,2023-02-04 03:01:26.725098189

In [13]:
df_purchases.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1737 entries, 0 to 1736
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   purchase_id     1737 non-null   object
 1   order_id        1737 non-null   object
 2   user_id         1737 non-null   object
 3   product_id      1737 non-null   object
 4   session_id      1737 non-null   object
 5   interaction_id  1737 non-null   object
 6   quantity        1737 non-null   int64
 7   unit_price      1737 non-null   float64
 8   total_amount    1737 non-null   float64
 9   order_date      1737 non-null   object
dtypes: float64(2), int64(1), object(7)
memory usage: 135.8+ KB

In [14]:
df_purchases.isnull().sum()

purchase_id       0
order_id          0
user_id           0
product_id        0
session_id        0
interaction_id    0
quantity          0
unit_price        0
total_amount      0
order_date        0
dtype: int64

In [15]:
df_products.head()

,product_id,product_name,product_description,category,subcategory,brand,price,rating_avg,review_count,stock_quantity,date_added
0,8826d916-cdfb-41c6-81ff-91a761565a70,The Elite Cipher - PlayStation 5 Edition,Bring joy to playtime with the The Elite Ciphe...,Toys & Games,Video Games,Hasbro,12.93,NaN,0,16,2024-09-04
1,2416da6e-c212-4ddb-8d88-00160eb686b2,KitchenAid Ultra-Soft Bedding,Designed to make your home more beautiful and ...,Home & Kitchen,Bedding,KitchenAid,31.65,2.0,1,12,2024-06-02
2,eb819333-b501-4c18-8c53-c786ed62c2f9,Mobil Premium Car Care,The Mobil Premium Car Care delivers profession...,Automotive,Car Care,Mobil,42.34,1.0,1,1,2024-03-26
3,71445abc-2f0d-4ac2-8097-acb7a3823bc9,Wilson Cycling - Navy,Engineered for peak performance in any conditi...,Sports & Outdoors,Cycling,Wilson,37.73,4.5,2,1,2023-06-19
4,13d16283-160e-4c20-aebd-f9d6297e4c73,Samsung Prime Prime15,Experience cutting-edge technology with the Sa...,Electronics,Smartphones,Samsung,123.44,3.5,2,2,2023-03-07

In [16]:
df_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           1000 non-null   object
 1   product_name         1000 non-null   object
 2   product_description  1000 non-null   object
 3   category             1000 non-null   object
 4   subcategory          1000 non-null   object
 5   brand                1000 non-null   object
 6   price                1000 non-null   float64
 7   rating_avg           452 non-null    float64
 8   review_count         1000 non-null   int64
 9   stock_quantity       1000 non-null   int64
 10  date_added           1000 non-null   object
dtypes: float64(2), int64(2), object(7)
memory usage: 86.1+ KB

In [17]:
df_products.isnull().sum()

product_id               0
product_name             0
product_description      0
category                 0
subcategory              0
brand                    0
price                    0
rating_avg             548
review_count             0
stock_quantity           0
date_added               0
dtype: int64

In [18]:
df_interactions.head()

,interaction_id,user_id,product_id,session_id,interaction_type,timestamp,dwell_time_ms
0,2ece1c7b-3244-4eeb-8d3e-f1b0cc09f20f,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,d3701c21-709a-4090-bab2-020261ce8a92,0003375f-8f69-44e1-9429-ec083de18495,view,2025-03-13 08:29:18.000000832,30481
1,bef097f8-4624-406a-9168-fc16f6d9db7a,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,d3701c21-709a-4090-bab2-020261ce8a92,0003375f-8f69-44e1-9429-ec083de18495,view,2025-03-13 08:29:50.726785665,37889
2,131590fb-aded-4eb2-b04a-158540271950,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,b1a8533d-7d06-48ae-b1d2-02a39ad1c623,0003375f-8f69-44e1-9429-ec083de18495,view,2025-03-13 08:30:37.244865920,11801
3,dda794be-afc4-4b8c-9a5c-3594d513f261,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,b1a8533d-7d06-48ae-b1d2-02a39ad1c623,0003375f-8f69-44e1-9429-ec083de18495,view,2025-03-13 08:30:37.244865920,11801
4,b68f3af4-29d1-4d85-884a-5e585d5d0a4a,8a49a58e-7e31-4616-8ac8-b1472ed4f5d8,2ee058a5-f098-4961-a46d-ba699b635b84,0003375f-8f69-44e1-9429-ec083de18495,add_to_wishlist,2025-03-13 08:30:50.152312822,1404

In [19]:
df_interactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   interaction_id    100000 non-null  object
 1   user_id           100000 non-null  object
 2   product_id        100000 non-null  object
 3   session_id        100000 non-null  object
 4   interaction_type  100000 non-null  object
 5   timestamp         100000 non-null  object
 6   dwell_time_ms     100000 non-null  int64
dtypes: int64(1), object(6)
memory usage: 5.3+ MB

In [20]:
df_interactions.isnull().sum()

interaction_id      0
user_id             0
product_id          0
session_id          0
interaction_type    0
timestamp           0
dwell_time_ms       0
dtype: int64

In [21]:
df_users["user_id"].duplicated().sum()

0

In [22]:
df_sessions["session_id"].duplicated().sum()

0

In [23]:
df_reviews["review_id"].duplicated().sum()

0

In [24]:
df_purchases["purchase_id"].duplicated().sum()

0

In [25]:
df_products["product_id"].duplicated().sum()

0

In [26]:
df_interactions["interaction_id"].duplicated().sum()

0

In [27]:
from sqlalchemy import create_engine

username = "postgres"
password = "root"
host = "localhost"
port = "5432"
database = "ecommerce_analyze"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

tables_to_load = {
    "users": df_users,
    "sessions": df_sessions,
    "reviews": df_reviews,
    "purchases": df_purchases,
    "products": df_products,
    "interactions" : df_interactions
}

for table_name, df_data in tables_to_load.items():
    df_data.to_sql(table_name, engine, if_exists="replace", index=False)
    print(f"Data Successfully Loaded into table '{table_name}' in database '{database}'.")

print("--- All 5 tables have been loaded successfully! ---")

Data Successfully Loaded into table 'users' in database 'ecommerce_analyze'.
Data Successfully Loaded into table 'sessions' in database 'ecommerce_analyze'.
Data Successfully Loaded into table 'reviews' in database 'ecommerce_analyze'.
Data Successfully Loaded into table 'purchases' in database 'ecommerce_analyze'.
Data Successfully Loaded into table 'products' in database 'ecommerce_analyze'.
Data Successfully Loaded into table 'interactions' in database 'ecommerce_analyze'.
--- All 5 tables have been loaded successfully! ---